### ISSUE TITLE
error in `pip install -e .`

### ISSUE THREAD

**Issue by booksource1** [THUDM/kgTransformer#2]
After i finished 
```
conda create -n kgTransformer python=3.8
conda activate kgTransformer
conda install "pytorch>=1.7.1,<=1.9" cudatoolkit=11.3 pyg -c pyg -c pytorch -y
conda install cudatoolkit-dev=11.3 "gxx_linux-64<=10" nccl -c conda-forge -y
git submodule update --init
cd fastmoe
```
when i run 
```
pip install -e .
```
have a error. The main error is
```
error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [85 lines of output]
        No CUDA runtime is found, using CUDA_HOME='/home/bk/miniconda3/envs/kgTransformer'
```
I can't solve this problem. Thank you for all your help.

**Comment by sshockwave** [comment]
Hi, thank you for your feedback!

Could you please ensure that proper NVIDIA drivers are installed by using the command

```bash
nvidia-smi
```

If it doesn't complain, we would suggest using the solution in another similar github issue https://github.com/open-mmlab/mmdetection/issues/281#issuecomment-625148676

```bash
export FORCE_CUDA="1"
```

In summary, this is a general CUDA issue that might arise in other projects as well. We would also recommend asking for help in the original [FastMoE](https://github.com/laekov/fastmoe) repo. We are using it as a dependency.

**Comment by booksource1** [comment]
Thank you for your help!

**Comment by booksource1** [comment]
I solved this issue by 
```
 pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/cu110/torch/

pip install torch-scatter==2.0.7 torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.7.1%2Bcu110.html

pip install -U -i https://pypi.tuna.tsinghua.edu.cn/simple torch_geometric

conda install cudatoolkit=11.3 cudatoolkit-dev=11.3 "gxx_linux-64<=10"

pip install -e .
```
Hope it can be helped.
